config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'fashions#index'

  resource :timeline, only:[:show]

  resources :fashions 

  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end

  post '/homes/guest_sign_in', to: 'homes#new_guest'

  resource :profile, only: [:show,:edit,:update]
  resources :favorites, only: [:index]

  namespace :api, defaults: {format: :json} do
    scope '/fashions/:fashion_id' do
      resources :comments, only:[:index,:create]
      resource :like, only: [:show, :create, :destroy]
    end
  end

end

app/models/fashion.rb
class Fashion < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }

  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_rich_text :other
  has_rich_text :description

  validates :image, presence: true
  validates :name, presence: true

  def like_count
    likes.count
  end
end

app/controllers/fashions_controller.rb
class FashionsController < ApplicationController
  before_action :profile
  before_action :loginuser_profile
  before_action :profile_show, only: [:show]

  def index
    @fashions = Fashion.all
  end

  def new
    @fashion = current_user.fashions.build
  end

  def create
    @fashion = current_user.fashions.build(fashion_params)
    if @fashion.save
      redirect_to root_path,notice: "投稿しました！"
    else
      flash.now[:error] = "投稿できませんでした"
      render :new
    end
  end

  def show
    @fashion = Fashion.find(params[:id])
    @fashion_user = @fashion.user
    @name = @fashion.name
    @image = @fashion.image
    @tops = @fashion.tops
    @pants = @fashion.pants
    @shoes = @fashion.shoes
    @other = @fashion.other
    @description = @fashion.description
  end

  def edit
    @fashion = current_user.fashions.find(params[:id])
  end

  def update
    @fashion = current_user.fashions.find(params[:id])
    @fashion.update(fashion_params)
    redirect_to fashion_path(@fashion),notice:"投稿を変更しました！"    
  end

  def destroy
    @fashion = current_user.fashions.find(params[:id])
    @fashion.destroy!
    redirect_to root_path,notice:"投稿を消去しました"
  end



  private
  
  def fashion_params
    params.require(:fashion).permit(
      :name,
      :tops,
      :pants,
      :shoes,
      :other,
      :description,
      :image)
  end

  def profile
    if user_signed_in?
      @profile = current_user.profile
    end
  end

  def loginuser_profile
    if user_signed_in?
      @loginuser_profile = current_user.profile
    end
  end


  def profile_show
    if user_signed_in?
      fashion = Fashion.find(params[:id])
      @profile = fashion.user.profile
    end
  end

end

app/views/fashions/_toppage.html.haml
.top
  .container
    .background
      %p.top_text
        　
        %br/
        　
        %br>/
        　自分のファッションを
        %br>/
        　　　　　　投稿しよう！
        %br/
        　　
        %br/
        　　　　　みんなのファッションを
        %br/
        　　　　　　　　　　　見てみよう！
        %br/
        　
        %br/
        　
        %br/
        　
        %br/
      %p.top_text_sub
        このアプリは自分のコーディネートを投稿し、
        %br/
        ユーザー同士で「今日」のファッションを
        %br>/
        見ることが出来るアプリです
        %br/
        　　
        %br/
    .top_image
      = image_tag  "img3.0.png", :size => '340x575' ,class:'posttoday'
    .second_image
      .second_image_content
        = image_tag  "t-shirt.jpg", :size => '168x217'
      .second_image_content
        = image_tag  "vans.jpg", :size => '168x217' ,class:'posttoday'
    .sign_up
      = link_to homes_guest_sign_in_path, method: :post do
        %p ゲストログイン
    .sign_up
      = link_to  new_user_registration_path do
        %p 新規登録はこちらから
    .sign_up
      = link_to  user_session_path do
        %p ログインはこちらから

app/views/fashions/edit.html.haml
.container
  %h2 Edit Fashion
  = form_with(model:@fashion ,url: fashion_path ,method: 'put' ,local: true) do |f|
    %div
      = f.label :image, 'Fashion', class:"label"
    .field
      = f.file_field :image
    %div
      = f.label :name, 'Name', class:"label"
    .field
      = f.text_field :name ,class: "text"
    %div
      = f.label :tops, 'Tops', class:"label"
    .field
      = f.text_field :tops ,class: "text"
    %div
      = f.label :pants, 'Pants', class:"label"
    .field
      = f.text_field :pants ,class: "text"
    %div
      = f.label :shoes, 'Shoes', class:"label"
    .field
      = f.text_field :shoes ,class: "text"
    %div
      = f.label :other, 'Other',class:"label"
    .field
      = f.text_area :other, class: "text_area"
    %div
      = f.label :description, 'Description',class:"label"
    .field
      = f.text_area :description, class: "text_area"
    %div
      = f.submit '投稿を変更する', class: "btn"

app/views/fashions/index.html.haml
.container
  - if user_signed_in?
    - if flash[:notice]
      %p.flash= flash[:notice]
    .tabs
      %div{:class => "#{'active' if current_page?(root_path)} tabs_item"}
        = link_to "新着記事一覧",root_path
      %div{:class => "#{'active' if current_page?(timeline_path)} tabs_item"}
        = link_to "タイムライン",timeline_path
    - @fashions.each do |f|
      = link_to fashion_path(f),class:"link_path" do
        .article
          .article_title
            .article_name
              = f.name
              %br/
            .article_image
              = image_tag(f.image) if f.image.attached?
              %br/
          .like_count
            いいね👍
            =f.like_count

          .article_content
            .article_content_name Tops
            = f.tops
            %br/
            .article_content_name Pants
            = f.pants
            %br/
            .article_content_name Shoes
            = f.shoes
            %br/
            .article_content_name Other
            = f.other
            %br/
            .article_content_name Description
            = f.description
            %br/
            .card_line
      .post_btn
        = link_to new_fashion_path, class:"link_path" do
          = image_tag  "鉛筆ボタン.png"
  - else
    = render 'toppage'

app/views/fashions/new.html.haml
.container
  %h2 New Fashion
  - if @fashion.errors.any?
    - @fashion.errors.full_messages.each do |message|
      .errors= message
  = form_with(model:@fashion ,url: fashions_path ,method: 'post' ,local: true) do |f|
    %div
      = f.label :image, 'Fashion', class:"label"
    .field
      = f.file_field :image
    %div
      = f.label :name, 'Name', class:"label"
    .field
      = f.text_field :name ,class: "text"
    %div
      = f.label :tops, 'Tops', class:"label"
    .field
      = f.text_field :tops ,class: "text"
    %div
      = f.label :pants, 'Pants', class:"label"
    .field
      = f.text_field :pants ,class: "text"
    %div
      = f.label :shoes, 'Shoes', class:"label"
    .field
      = f.text_field :shoes ,class: "text"
    %div
      = f.label :other, 'Other',class:"label"
    .field
      = f.rich_text_area :other, class: "text_area"
    %div
      = f.label :description, 'Description',class:"label"
    .field
      = f.rich_text_area :description, class: "text_area"
    %div
      = f.submit '投稿する', class: "btn"

app/views/fashions/show.html.haml
.container#fashion-show{data: {fashion_id: @fashion.id}}
  - if user_signed_in?
    - if flash[:notice]
      %p.flash= flash[:notice]
    .article
      .article_title
        .article_name
          = @name
          %br/
        .article_image
          = image_tag(@image) if @image.attached?
          %br/
      .article_content
        .dropdown
          - if current_user.fashions.exists?(id: @fashion.id)
            = image_tag 'dot.png' ,class:"dot"
            .dropdown_content
              = link_to "Edit", edit_fashion_path(params[:id])
              = link_to "delete", fashion_path(params[:id]), data: {method: 'delete', confirm:"本当に削除しても良いですか？"}
        
        .index_avatar
          = link_to account_path(params[:id]) ,class:"link_path" do
            - if @fashion_user.profile&.avatar&.attached?
              = image_tag(@profile.avatar) if @profile.avatar.attached?
              %div= @profile.nickname
            - else
              = image_tag 'avatar.png' ,:size => '50x50'
          

        .heart.hidden.active-heart
          = image_tag 'heart-active.svg'

        .heart.hidden.inactive-heart
          = image_tag 'heart.svg'

        .article_content_name Tops
        = @tops
        %br/
        .article_content_name Pants
        = @pants
        %br/
        .article_content_name Shoes
        = @shoes
        %br/
        .article_content_name Other
        = @other
        %br/
        .article_content_name Description
        = @description
        %br/
        .line
    .comment_title
      %h2 コメント一覧
    .comment_container


    .new_comment.show-comment-form
      .user_comment
        コメントを追加
    .comment_text_area.hidden
      = text_area_tag :comment_comment, '',placeholder: "コメントを入力" ,class: 'text_area_comment'
      .new_comment.add-comment-button
        .user_comment 
          コメントを追加

  - else
    = render 'toppage'
  = javascript_pack_tag 'fashion'