config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'fashions#index'

  resource :timeline, only:[:show]

  resources :fashions 

  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end

  post '/homes/guest_sign_in', to: 'homes#new_guest'

  resource :profile, only: [:show,:edit,:update]
  resources :favorites, only: [:index]

  namespace :api, defaults: {format: :json} do
    scope '/fashions/:fashion_id' do
      resources :comments, only:[:index,:create]
      resource :like, only: [:show, :create, :destroy]
    end
  end

end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  before_action :authenticate_user!
  before_action :profile
  before_action :loginuser_profile

  def show
    user_ids = current_user.followings.pluck(:id)
    @fashions = Fashion.where(user_id: user_ids)
  end



  private

  def loginuser_profile
    if user_signed_in?
      @loginuser_profile = current_user.profile
    end
  end

  def profile
    if user_signed_in?
      @profile = current_user.profile
    end
  end
end

app/views/timelines/show.html.haml
.container
  .tabs
    %div{:class => "#{'active' if current_page?(root_path)} tabs_item"}
      = link_to "新着記事一覧",root_path
    %div{:class => "#{'active' if current_page?(timeline_path)} tabs_item"}
      = link_to "タイムライン",timeline_path
  - @fashions.each do |f|
    = link_to fashion_path(f),class:"link_path" do
      .article_title
        .article_name
          = f.name
          %br/
        .article_image
          = image_tag(f.image) if f.image.attached?
          %br/
      .article_content
        .article_content_name Tops
        = f.tops
        %br/
        .article_content_name Pants
        = f.pants
        %br/
        .article_content_name Shoes
        = f.shoes
        %br/
        .article_content_name Other
        = f.other
        %br/
        .article_content_name Description
        = f.description
        %br/
        .card_line