config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'fashions#index'

  resource :timeline, only:[:show]

  resources :fashions 

  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end

  post '/homes/guest_sign_in', to: 'homes#new_guest'

  resource :profile, only: [:show,:edit,:update]
  resources :favorites, only: [:index]

  namespace :api, defaults: {format: :json} do
    scope '/fashions/:fashion_id' do
      resources :comments, only:[:index,:create]
      resource :like, only: [:show, :create, :destroy]
    end
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PostToday
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=davice-width, initial-scale=1.0", :name => "viewport"}/
  %body
  .container
    %header.header
      - if user_signed_in?
        .dropdown
          .avatar
            - if current_user.profile&.avatar&.attached?
              = image_tag(@loginuser_profile.avatar) if @profile.avatar.attached?
            - else
              = image_tag 'avatar.png' ,:size => '50x50'
            .dropdown_content
              = link_to "プロフィール", profile_path
              = link_to "お気に入り一覧", favorites_path
              = link_to "ログアウト", destroy_user_session_path, method: :delete
        = link_to root_path,class:"link_path" do
          %h2 PostToday
          .line  
      - else
        .dropdown
          .avatar
            = image_tag 'avatar.png' ,:size => '50x50'
            .dropdown_content
              = link_to "新規登録", new_user_registration_path
              = link_to "ログイン", user_session_path
        .container
          = link_to root_path,class:"link_path" do
            %h2 PostToday
        .line
    = yield