config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'fashions#index'

  resource :timeline, only:[:show]

  resources :fashions 

  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end

  post '/homes/guest_sign_in', to: 'homes#new_guest'

  resource :profile, only: [:show,:edit,:update]
  resources :favorites, only: [:index]

  namespace :api, defaults: {format: :json} do
    scope '/fashions/:fashion_id' do
      resources :comments, only:[:index,:create]
      resource :like, only: [:show, :create, :destroy]
    end
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :profile
  before_action :loginuser_profile

  def show
    fashion = Fashion.find(params[:id])
    @user = fashion.user
    @profile = @user.profile
    if @user == current_user
      redirect_to profile_path
    end
  end

  private

  def profile
    if user_signed_in?
      @profile = current_user.profile
    end
  end

  def loginuser_profile
    if user_signed_in?
      @loginuser_profile = current_user.profile
    end
  end

end

app/views/accounts/show.html.haml
.container
  .profile_avatar
    - if @user.profile&.avatar&.attached?
      = image_tag(@profile.avatar)
    - else
      = image_tag 'avatar.png' ,:size => '50x50'

  - if @user.profile&.avatar&.attached?
    .profile_content
      .profile_name
        = @profile.nickname
      .profile_introduction
        = @profile.introduction
      - if @user == current_user
        = link_to edit_profile_path(current_user) do
          = image_tag 'profile.png',:size => '150x30' ,class:"profile_update"

      - else
        - if current_user&.has_followed?(@user)
          = link_to account_unfollows_path(@user), method: :post,class:"link_path" do
            %p.unfollow_btn フォローをはずす
            
        - else
          = link_to account_follows_path(@user), method: :post,class:"link_path" do
            %p.follow_btn フォローする
            
  - else
    .profile_content
      .profile_name
        %h3 No Name
      .profile_introduction
        %h3 No introduction
  .profile_line
  %h2
    = @profile.nickname
    さんの投稿
  - @user.fashions.each do |f|
    .article
      .article_title
        .article_name
          = f.name
          %br/
        .article_image
          = image_tag(f.image) if f.image.attached?
          %br/
      .like_count
        いいね👍
        =f.like_count
      .card_line